// <auto-generated />
using System;
using FieldEngineerApi.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FieldEngineerApi.Migrations.Inventory
{
    [DbContext(typeof(InventoryContext))]
    [Migration("20210316114941_AddImageToAppointment")]
    partial class AddImageToAppointment
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.3")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("FieldEngineerApi.Models.BoilerPart", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CategoryId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NumberInStock")
                        .HasColumnType("int");

                    b.Property<string>("Overview")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("money");

                    b.HasKey("Id");

                    b.ToTable("BoilerParts");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CategoryId = "Flange",
                            Name = "Caserta Stone Beige",
                            NumberInStock = 25,
                            Overview = "Extreme Series 18 in. x 18 in. carpet tiles are a durable and beautiful carpet solution specially engineered for both indoor and outdoor residential installations.",
                            Price = 8.1m
                        },
                        new
                        {
                            Id = 2L,
                            CategoryId = "Sprocket",
                            Name = "Caserta Sky Grey",
                            NumberInStock = 30,
                            Overview = "Extreme Series 18 in. x 18 in. carpet tiles are a durable and beautiful carpet solution specially engineered for both indoor and outdoor residential installations.",
                            Price = 8.1m
                        },
                        new
                        {
                            Id = 3L,
                            CategoryId = "Boiler",
                            Name = "Ageless Beauty Clay",
                            NumberInStock = 5,
                            Overview = "Add some fashion to your floors with the Shaw Ageless Beauty Carpet collection.",
                            Price = 1.98m
                        },
                        new
                        {
                            Id = 4L,
                            CategoryId = "Exchanger",
                            Name = "Lush II Tundra",
                            NumberInStock = 12,
                            Overview = "Made with 100% premium nylon fiber, this textured carpet creates a warm, casual atmosphere that invites you to relax and thoroughly enjoy your home.",
                            Price = 3.79m
                        });
                });

            modelBuilder.Entity("FieldEngineerApi.Models.Order", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("BoilerPartId")
                        .HasColumnType("bigint");

                    b.Property<bool>("Delivered")
                        .HasColumnType("bit");

                    b.Property<DateTime>("DeliveredDateTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("OrderedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("money");

                    b.Property<long>("quantity")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("BoilerPartId");

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            BoilerPartId = 1L,
                            Delivered = false,
                            DeliveredDateTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            OrderedDateTime = new DateTime(2021, 3, 11, 11, 49, 41, 542, DateTimeKind.Local).AddTicks(9476),
                            TotalPrice = 243.0m,
                            quantity = 30L
                        },
                        new
                        {
                            Id = 2L,
                            BoilerPartId = 3L,
                            Delivered = true,
                            DeliveredDateTime = new DateTime(2021, 3, 12, 11, 49, 41, 545, DateTimeKind.Local).AddTicks(7044),
                            OrderedDateTime = new DateTime(2021, 3, 9, 11, 49, 41, 545, DateTimeKind.Local).AddTicks(7018),
                            TotalPrice = 39.6m,
                            quantity = 20L
                        });
                });

            modelBuilder.Entity("FieldEngineerApi.Models.Order", b =>
                {
                    b.HasOne("FieldEngineerApi.Models.BoilerPart", "BoilerPart")
                        .WithMany("Orders")
                        .HasForeignKey("BoilerPartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BoilerPart");
                });

            modelBuilder.Entity("FieldEngineerApi.Models.BoilerPart", b =>
                {
                    b.Navigation("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
